-- Generated by Ryoku Settings (Keybinds page); change it in the GUI, not here.
return {
	["SUPER + Return"] = "SUPER + T",
	["XF86AudioNext"] = "SUPER + SHIFT + N",
	["XF86AudioPlay"] = "SUPER + CTRL + Space",
	["XF86AudioPrev"] = "SUPER + SHIFT + P",
}
