-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { gaps_in = 5, gaps_out = 10 },
  decoration = { rounding = 15, inactive_opacity = 0.95, blur = { size = 3 } },
  input = { kb_layout = "us", kb_variant = "intl", kb_options = "", follow_mouse = 1, accel_profile = "flat" },
  misc = { middle_click_paste = false },
})

hl.curve("ryokuBloom", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1.0 } } })
hl.curve("ryokuWobble", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1.0 } } })

hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "23")
hl.env("HYPRCURSOR_THEME", "Adwaita")
hl.env("HYPRCURSOR_SIZE", "23")

hl.env("TERMINAL", "ghostty")

hl.bind("SUPER + C", hl.dsp.exec_cmd("/home/joaocunha50/.local/zed.app/bin/zed"))

hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor Adwaita 23")
  hl.exec_cmd("ghostty")
end)
