# Toggle mouse support
set -g mouse on

# Toggle status bar
bind b set-option -g status

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g status-justify centre # center the window list in status line

set -g status-left-length 50
set -g status-left "#S #{?client_prefix,#[fg=colour208]^S,}" # modify the default left status bar, rm `[]`

set -g status-right "#(~/.local/bin/battery) #[fg=purple]%d %b %R"

# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

run '~/.config/tmux/plugins/tpm/tpm'
